// Arquivo de definições de idioma (carregado via script tag para evitar CORS local)
const I18N_DATA = {
    "pt-br": {
        "import_json": "Importar JSON",
        "import_media": "Importar Mídia",
        "add_subtitle": "Adicionar Legenda",
        "save": "Salvar",
        "play": "Play",
        "pause": "Pausar",
        "mode_916": "Modo 9:16",
        "mode_169": "Modo 16:9",
        "auto_chars": "Gerar nível caractere automaticamente",
        "layer": "Camada",
        "zoom": "Zoom",
        "no_selection": "Selecione uma legenda",
        "no_media": "Nenhum vídeo ou áudio carregado",
        "export_title": "Exportar Legendas",
        "format": "Formato",
        "track_mode": "Camada",
        "track_active": "Apenas Camada Ativa",
        "track_all": "Todas as Camadas (JSON único)",
        "cancel": "Cancelar",
        "export_now": "Exportar Agora",
        "split_punctuation": "Dividir por Pontuação",
        "new_subtitle_text": "Nova legenda",
        "prompt_new_track": "Nome da nova camada:",
        "prompt_max_chars": "Máximo de caracteres por bloco (0 para dividir em todas as pontuações):",
        "track_prefix": "Track",
        "split": "Dividir (K)",
        "copy": "Copiar (Ctrl+C)",
        "delete": "Deletar (Del)",
        "merge": "Mesclar (G)",
        "paste": "Colar (Ctrl+V)",
        "undo": "Desfazer (Ctrl+Z)",
        "redo": "Refazer (Ctrl+Y)",
        "export_json_whisperx": "JSON (WhisperX)",
        "export_json_premiere": "JSON (Adobe Premiere)",
        "find_title": "Buscar",
        "replace_title": "Buscar e Substituir",
        "find_placeholder": "Buscar...",
        "replace_placeholder": "Substituir por...",
        "find_next": "Próximo",
        "find_previous": "Anterior",
        "replace_one": "Substituir",
        "replace_all": "Substituir Todos",
        "close": "Fechar",
        "results_count": "resultados",
        "no_results": "Nenhum resultado encontrado"
    },
    "en": {
        "import_json": "Import JSON",
        "import_media": "Import Media",
        "add_subtitle": "Add Subtitle",
        "save": "Save",
        "play": "Play",
        "pause": "Pause",
        "mode_916": "9:16 Mode",
        "mode_169": "16:9 Mode",
        "auto_chars": "Auto-generate character level",
        "layer": "Layer",
        "zoom": "Zoom",
        "no_selection": "Select a subtitle",
        "no_media": "No video or audio loaded",
        "export_title": "Export Subtitles",
        "format": "Format",
        "track_mode": "Track",
        "track_active": "Active Track Only",
        "track_all": "All Tracks (Single JSON)",
        "cancel": "Cancel",
        "export_now": "Export Now",
        "split_punctuation": "Split by Punctuation",
        "new_subtitle_text": "New subtitle",
        "prompt_new_track": "New track name:",
        "prompt_max_chars": "Max characters per block (0 to split at every punctuation):",
        "track_prefix": "Track",
        "split": "Split (K)",
        "copy": "Copy (Ctrl+C)",
        "delete": "Delete (Del)",
        "merge": "Merge (G)",
        "paste": "Paste (Ctrl+V)",
        "undo": "Undo (Ctrl+Z)",
        "redo": "Redo (Ctrl+Y)",
        "export_json_whisperx": "JSON (WhisperX)",
        "export_json_premiere": "JSON (Adobe Premiere)",
        "find_title": "Find",
        "replace_title": "Find and Replace",
        "find_placeholder": "Find...",
        "replace_placeholder": "Replace with...",
        "find_next": "Next",
        "find_previous": "Previous",
        "replace_one": "Replace",
        "replace_all": "Replace All",
        "close": "Close",
        "results_count": "results",
        "no_results": "No results found"
    }
};